### ISSUE TITLE
Scan some fields from ID CARD's with accuracy ?

### ISSUE THREAD

**Issue by achinverma** [BlinkOCR/blinkocr-android#1]
hi , i am using this library to perform scans of various ID cards in my app. i am scanning the below image to get fields ame, fathers name, sex, age, address , date, as you can see in the sample image below.

but i am not getting accurate results , i am getting some useless characters in the output after scanning the  ID card, please can you suggest me how can extract the mentioned above fields with  accuracy ?
i want to extract the fields  and i wan to show in form in next activity after scanning successfully , so can you guide me what are the things that i 
have to change in your OCR demo? 
![voter_card](https://cloud.githubusercontent.com/assets/2811593/10161423/b20983ca-66c1-11e5-9aa0-e2f1ecaa04c8.JPG)

**Comment by DoDoENT** [comment]
Hi,
you should change the OCR demo in following way:
- use only Raw parser - instatiate it multiple time for each field you need to have scanned
- while scanning, ensure only text that is required to be scanned is inside scanning area, not the text that shouldn't be read
- depending on light conditions and quality of the camera in device being used, it is possible to have misrecognitions - you need to design your data extraction code with that in mind

If you want more control over BlinkOCR process, you can modify custom UI demo's [ScanActivity](https://github.com/BlinkOCR/blinkocr-android/blob/master/BlinkOCRDemo/BlinkOCRApp/src/main/java/com/microblink/ocr/ScanActivity.java) and each time you [receive scan result](https://github.com/BlinkOCR/blinkocr-android/blob/master/BlinkOCRDemo/BlinkOCRApp/src/main/java/com/microblink/ocr/ScanActivity.java#L279) you can use raw OCR result to extract required data, considering [OCR char recognition variants](https://blinkocr.github.io/blinkocr-android/com/microblink/results/ocr/OcrChar.html#getRecognitionVariants%28%29) and [time redundancy](https://blinkocr.github.io/blinkocr-android/com/microblink/recognizers/ocr/blinkocr/parser/generic/RawParserSettings.html#setUseSieve%28boolean%29). 

To get a better understanding of BlinkOCR's scanning process, consider reading [documentation](https://github.com/BlinkOCR/blinkocr-android#blinkOCR) and playing with our demo app. Also, bear in mind that OCR engine will [never be able to give you 100% correct results](https://en.wikipedia.org/wiki/Optical_character_recognition#Accuracy), but using different [OCR engine parameters](https://blinkocr.github.io/blinkocr-android/com/microblink/recognizers/ocr/blinkocr/parser/generic/RawParserSettings.html#setOcrEngineOptions%28com.microblink.recognizers.ocr.blinkocr.engine.BlinkOCREngineOptions%29) you might achieve very good results.

**Comment by achinverma** [comment]
thanks for your reply @DoDoENT 
i will try and update you , if i got any issue.

**Comment by achinverma** [comment]
hi @DoDoENT , i have scanned an image, i will share the image below , but that image is same as in my first comment , i have scanned the first part of the image , actually it was voter card id of india , which will contain two Languages one is ENGLISH and Other is Hindi ,i want to extract the English lines  
when i   scanned the image i got got some better results ,but i want to improve this results , so please can you guide me to do this
and about my code , i have used this image 
![voterid3](https://cloud.githubusercontent.com/assets/2811593/10213707/40d06f5c-682e-11e5-8b52-fe7db5bbe387.jpg)

and i have placed in assets folder and then i am reading this image from assets folder to Bitmap
this is my complete code 
https://gist.github.com/achinverma/c53db4889f1bb8178492
and my output after scanning is 
as you can on the left side of the image which i scanned and you see the results on the right of the image 
![device-2015-10-01-102126](https://cloud.githubusercontent.com/assets/2811593/10213749/c26f96d2-682e-11e5-8c78-bf6ee82914fe.png)

 £
 ,4_Rö \* *'_T@"
 us== qa
 ELeCTlON coMM SSION OF !NDA
: NLN1016971
 -<:s?š_-
 £)
 f
 xz?v<ran av<Ta :s?seä Ž5T #+T
 Eiectoćs Name : lttpel Deka Barooah
 üam m=m :fŽ?@T_ä W3RT
 Fathe(s Name :Nityamanda Barooah
 fäm / SeX :W/ Male
 l.1 2008 =Ü 3TI3
 Age as onii 2008
 39

**Comment by DoDoENT** [comment]
Hi @achinverma,

the problem is that you are trying to scan the whole image and this confuses the OCR engine because it tries to read both Hindi and English (OCR does not understand Hindi).

If using DirectAPI, I suggest using method [recognize](https://blinkocr.github.io/blinkocr-android/com/microblink/directApi/Recognizer.html#recognize%28android.graphics.Bitmap, com.microblink.geometry.Rectangle, com.microblink.view.recognition.ScanResultListener%29) which also receives scanning region. The region should be set as region in image that needs to be scanned (for example region around text containing elector's name). The position of that region should be determined by you for each image you are scanning.

If you plan to scan voter with device's camera, then I recommend checking out [BlinkOCR demo app](https://github.com/BlinkOCR/blinkocr-android/tree/master/BlinkOCRDemo/BlinkOCRApp).
