### ISSUE TITLE
Applying black and white filter

### ISSUE THREAD

**Issue by ckygel** [BlinkOCR/blinkocr-android#13]
Hi,

I'm having trouble detecting color texts with blinkOCR, and I think applying black / white filter to camera will help. Is there a way to apply this in blinkOCR's BlinkInputSegmentDemo app?

**Comment by DoDoENT** [comment]
Hi!

There is no possibility to apply any filters to camera in BlinkOCR, however if you want to scan coloured text, you can disable colour drop in OCR engine settings with method [setColorDroputEnabled](https://blinkinput.github.io/blinkinput-android/com/microblink/recognizers/blinkocr/engine/BlinkOCREngineOptions.html#setColorDropoutEnabled-boolean-). By default, this feature is enabled, as it increases the recognition quality of black and white text, but makes it difficult to process coloured text. [Raw parser](https://blinkinput.github.io/blinkinput-android/com/microblink/recognizers/blinkocr/parser/generic/RawParserSettings.html) and [regex parser](https://blinkinput.github.io/blinkinput-android/com/microblink/recognizers/blinkocr/parser/regex/RegexParserSettings.html) support setting custom [OCR engine settings](https://blinkinput.github.io/blinkinput-android/com/microblink/recognizers/blinkocr/engine/BlinkOCREngineOptions.html).

**Comment by ckygel** [comment]
@DoDoENT Thanks! I will try it out!

**Comment by ckygel** [comment]
I've disabled setColorDroputEnabled and it works perfectly!
