### ISSUE TITLE
Problem on handwritten text recognition

### ISSUE THREAD

**Issue by csyuab** [BlinkOCR/blinkocr-android#15]
So far we have got some troubles on recognising handwritten texts. Are there any method we can improve the handwriting recognition or any feature related to that in the blinkOCR's BlinkInputSegmentDemo app?

**Comment by i1E** [comment]
Hi @csyuab,

we do not support recognition of handwritten text yet.

**Comment by csyuab** [comment]
Thanks for your reply,

May I know can we build our own neural network for training the handwritten text recognition while using the BlinkOCR?

**Comment by i1E** [comment]
Unfortunately, this is not supported and you cannot add handwritten support to our SDK.

**Comment by csyuab** [comment]
Okay I see. Thanks a lot for your reply!
