### ISSUE TITLE
native library with phonegap

### ISSUE THREAD

**Issue by kresovic-milos** [BlinkOCR/blinkocr-android#2]
Hi,

First of all, thank you for this great library!

Is it possible to use blinkocr in phonegap project?
If it is, is there something in particular about integration I should know about or it's standard procedure?

**Comment by DoDoENT** [comment]
Hi Milos,

we currently do not offer official PhoneGap plugin, however you can create your own that wraps the android library. You can see an example of how to do that in our [PDF417.mobi project](https://github.com/PDF417/pdf417-phonegap) for which we do have PhoneGap plugin.

The API of PDF417.mobi and BlinkOCR is very similar so creating your own PhoneGap wrapper should not be an issue.

**Comment by kresovic-milos** [comment]
Ok, thanks again
