### ISSUE TITLE
EXTRAS_SHOW_OCR_RESULT does not work

### ISSUE THREAD

**Issue by aldrinarciga** [BlinkOCR/blinkocr-android#4]
I tried adding this code :
`intent.putExtra(BlinkOCRActivity.EXTRAS_SHOW_OCR_RESULT, false);`

But when the activity BlinkOCRActivity starts, the preview(green box with text) is still visible.

**Comment by DoDoENT** [comment]
I've just tested that with [simple integration demo](https://github.com/BlinkOCR/blinkocr-android/blob/master/BlinkOCRDemo/BlinkOCRSegmentDemo/src/main/java/com/microblink/ocr/MainActivity.java#L49) and it works. Can you provide a minimal example app in which this extra does not work?

**Comment by aldrinarciga** [comment]
Here is my method on calling the activity:

```
protected void onResume() {
        super.onResume();
        Intent intent = new Intent(this, BlinkOCRActivity.class);
        intent.putExtra(BlinkOCRActivity.EXTRAS_LICENSE_KEY, "32UP5GIX-YNI7S3NW-IYEZ63EM-E4HY53J6-X6D4M2W4-2NPVEEBY-V2OBQLJJ-Z7ZI5T4M");

        ScanConfiguration[] confArray = new ScanConfiguration[] {
                new ScanConfiguration(R.string.raw_title, R.string.raw_msg, "Raw", new RawParserSettings())
        };
        intent.putExtra(BlinkOCRActivity.EXTRAS_SCAN_CONFIGURATION, confArray);
        intent.putExtra(BlinkOCRActivity.EXTRAS_SHOW_OCR_RESULT, false);
        startActivityForResult(intent, MY_REQUEST_CODE);

    }
```

But, as I've said earlier, the preview(green box with text) is still visible.

**Comment by i1E** [comment]
Hi @aldrinarciga,

You can not disable this preview in the provided BlinkOCRActivity, scan result has to be shown to user in some way, this is the purpose of that activity. With BlinkOCRActivity.EXTRAS_SHOW_OCR_RESULT you can control whether or not the results are shown above scanning window (chars or animated dots). If you want to build your custom scan activity, check [BlinkOCRSegment demo app](https://github.com/BlinkOCR/blinkocr-android/tree/master/BlinkOCRDemo/BlinkOCRSegmentDemo) example.

**Comment by aldrinarciga** [comment]
Oh okay I got it, sorry I got confused. Thanks.
