### ISSUE TITLE
SegmentScanActivity customization

### ISSUE THREAD

**Issue by JPierron** [BlinkOCR/blinkocr-android#9]
Hi,

I was wondering if there was any way to customize the SegmentScanActivity layout.
Specifically, I'd like to customize the validation layout (the green part) by moving the validation button to the bottom/end or bottom/start of the validation layout (This button, positionned in the middle of the screen, is not very practical to use in landscape mode).

Is that doable ?

Thanks.

Regards.

**Comment by i1E** [comment]
Hi @JPierron,

if you use provided SegmentScanActivity, all possible customisation options are listed [here](https://github.com/BlinkOCR/blinkocr-android#-customization-of-segmentscanactivity-activity). Additionally, you have few options to customise the size of the scanning window with [ScanConfiguration](https://blinkocr.github.io/blinkocr-android/com/microblink/ocr/ScanConfiguration.html). You cannot customise the result overlay (validation layout). If you want to customise this part of the layout, you should build your own scan activity. You can use the [BlinkOCRSegmentDemo](https://github.com/BlinkOCR/blinkocr-android/tree/master/BlinkOCRDemo/BlinkOCRSegmentDemo) app as an example.

Best regards
